<div class="post">
	                		<div class="content">
	                			<div class="art_img">
	                				<a href="[field:arcurl/]" rel="bookmark">
	                					<img src="[field:litpic/]" alt="[field:fulltitle/]" />
	                				</a>
	                			</div>
	                			<div class="art_right">
	                				<h4><a href="[field:arcurl/]" rel="bookmark">[field:fulltitle/]</a></h4>
	                				<div class="postmeta">
	                					baoqger<span class="left_author_span">[field:pubdate function="GetDateTimeMK(@me)"/]</span>&nbsp;<em class="tag"><span class='left_tag_span'>[field:id function=GetTags(@me)/]</span></em>
	                				</div>
	                				<p class="summary">
[field:description function='cn_substr(@me,130)'/]...<a rel="bookmark" href="[field:arcurl/]"></a>
	                				</p>
	                			</div>
	                		</div>
	                	</div>