<li class="display" id="image_[field:global name=autoindex/]">
	            			<a title="[field:fulltitle/]" rel="bookmark" href="[field:arcurl/]">
	            				<img width="670px" height="330px"  src="[field:litpic/]" alt="[field:fulltitle/]">
	            			</a>
	            			<div class="word" style="opacity: 0.85; display: block;"><a title="[field:fulltitle/]" rel="bookmark" href="http://www.kuailiyu.com/article/5214.html">[field:fulltitle/]</a></div>
	            		</li>