<?php
$z[0]=Array("global","",195,221);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",260,285);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("field","(@me==\"\")? @me=\"<em></em>\":@me=\"\";",305,389);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n      	<a href='[field:typeurl/]'>[field:typename/]</a>\r\n      	",399,574);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<a href='~typelink~'><em></em>~typename~</a>";

?>