<?php
$z[0]=Array("arcurl","",171,186);
$z[1]=Array("litpic","",255,270);
$z[2]=Array("fulltitle","",277,295);
$z[3]=Array("arcurl","",489,504);
$z[4]=Array("fulltitle","",521,539);
$z[5]=Array("writer","",662,677);
$z[6]=Array("pubdate","",771,817);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("id","",874,907);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("description","",1020,1070);
$z[8][4]['function']="cn_substr(@me,130)";
$z[9]=Array("arcurl","",1097,1112);

?>