<?php
$z[0]=Array("arcurl","",135,150);
$z[1]=Array("litpic","",201,216);
$z[2]=Array("fulltitle","",223,241);
$z[3]=Array("arcurl","",381,396);
$z[4]=Array("fulltitle","",413,431);
$z[5]=Array("pubdate","",547,593);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("id","",650,683);
$z[6][4]['function']="GetTags(@me)";
$z[7]=Array("description","",768,818);
$z[7][4]['function']="cn_substr(@me,120)";
$z[8]=Array("arcurl","",845,860);

?>