<?php
$z[0]=Array("arcurl","",171,186);
$z[1]=Array("litpic","",255,270);
$z[2]=Array("fulltitle","",277,295);
$z[3]=Array("arcurl","",489,504);
$z[4]=Array("title","",521,535);
$z[5]=Array("writer","",658,673);
$z[6]=Array("pubdate","",767,813);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("id","",870,903);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("description","",1016,1036);
$z[9]=Array("arcurl","",1060,1075);

?>