<?php
$z[0]=Array("global","",140,166);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("flink","",500,538);
$z[1][4]['linktype']="2";
$z[1][4]['row']="100";
$z[2]=Array("arclist","\r\n<a href=\"[field:arcurl/]\" target=\"_blank\" rel=\"nofollow\">[field:title/]</a> |                 \r\n       ",929,1081);
$z[2][4]['typeid']="7";
$z[2][4]['row']="10";
$z[3]=Array("global","",1236,1262);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",1264,1288);
$z[4][4]['name']="cfg_beian";

?>