<?php
$z[0]=Array("global","",172,198);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",237,262);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("field","(@me==\"\")? @me=\"<em></em>\":@me=\"\";",282,366);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n      	<a href='[field:typeurl/]'>[field:typename/]</a>\r\n      	",376,551);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<a href='~typelink~'><em></em>~typename~</a>";

?>