<?php
$z[0]=Array("global","",127,152);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("arclist","\r\n\r\n            	            	                <li>\r\n                    <span class=\"ph_span\">[field:global runphp='yes' name=autoindex]if(@me<=9) @me = '0'.@me;if(@me==10) @me=@me;[/field:global]</span>\r\n                    <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\" class=\"sky_blue\" target=\"_blank\">[field:title/]</a>\r\n                </li>\r\n                \r\n       ",818,1255);
$z[1][4]['sort']="hot";
$z[1][4]['subday']="7";
$z[1][4]['row']="10";
$z[2]=Array("arclist","\r\n\r\n            	            	                <li>\r\n                    <span class=\"ph_span\">[field:global runphp='yes' name=autoindex]if(@me<=9) @me = '0'.@me;if(@me==10) @me=@me;[/field:global]</span>\r\n                    <a title=\"[field:fulltitle/]\" href=\"[field:arcurl/]\" class=\"sky_blue\" target=\"_blank\">[field:title/]</a>\r\n                </li>\r\n                \r\n       ",1415,1853);
$z[2][4]['sort']="hot";
$z[2][4]['subday']="30";
$z[2][4]['row']="10";
$z[3]=Array("myad","",2051,2086);
$z[3][4]['name']="indexTopBanner2";
$z[4]=Array("tag","\r\n            <a href='[field:link/]' style=\"color:;font-size:16px;\">[field:tag /]</a>&nbsp;&nbsp;&nbsp;\r\n          ",2270,2440);
$z[4][4]['row']="10";
$z[4][4]['getall']="1";
$z[4][4]['sort']="month";
$z[5]=Array("myad","",2547,2582);
$z[5][4]['name']="innerTopBanner1";
$z[6]=Array("arclist","\r\n\r\n                        <li>\r\n                <div class=\"pic\">\r\n                    <a href=\"[field:arcurl/]\" target=\"_blank\"><img width=\"90\" height=\"60\" src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\" /></a>\r\n                </div>\r\n                <p><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">  [field:title/]</a></p>\r\n            </li>\r\n         ",2739,3175);
$z[6][4]['flag']="c";
$z[6][4]['titlelen']="42";
$z[6][4]['row']="6";
$z[7]=Array("myad","",3309,3338);
$z[7][4]['name']="right_ad3";

?>